# Generated by Django 4.2.16 on 2026-06-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('detected_label', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('detected_color', models.CharField(blank=True, max_length=50)),
                ('color_hex', models.CharField(blank=True, max_length=10)),
                ('clip_description', models.CharField(blank=True, max_length=500)),
                ('fashion_attributes', models.JSONField(blank=True, default=dict)),
                ('google_lens_data', models.JSONField(blank=True, default=dict)),
                ('search_keyword', models.CharField(blank=True, max_length=255)),
                ('classifier_phase', models.CharField(default='mobilenet', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('price_numeric', models.FloatField(default=0.0)),
                ('discount', models.CharField(blank=True, max_length=50)),
                ('rating', models.CharField(blank=True, max_length=20)),
                ('product_image', models.URLField(blank=True, max_length=1000)),
                ('product_link', models.URLField(max_length=1000)),
                ('delivery', models.CharField(blank=True, max_length=100)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.searchhistory')),
            ],
        ),
    ]
