# Generated by Django 4.2.16 on 2026-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_googlelensresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlelensresult',
            name='price_numeric',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='googlelensresult',
            name='reviews',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='googlelensresult',
            name='result_type',
            field=models.CharField(choices=[('shopping', 'Shopping Result'), ('visual', 'Visual Match')], default='visual', max_length=10),
        ),
    ]
