# Generated by Django 4.2.16 on 2026-06-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_googlelensresult_price_numeric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlelensresult',
            name='delivery',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='googlelensresult',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='googlelensresult',
            name='scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlelensresult',
            name='scraped_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='googlelensresult',
            name='scraped_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='googlelensresult',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.googlelensresult'),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='googlelensresult',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
