# Generated by Django 4.2.16 on 2026-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_googlelensresult_delivery_googlelensresult_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
