# Generated by Django 4.2.16 on 2026-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_last_scraped_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlelensresult',
            name='image_url',
            field=models.URLField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='googlelensresult',
            name='link',
            field=models.URLField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='googlelensresult',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(max_length=3000),
        ),
    ]
